/**
 * Curadoria do catalogo do wger.
 *
 * O wger e colaborativo: o mesmo endpoint devolve supino reto e "Child's pose".
 * Este arquivo e a camada humana em cima disso — o que entra, o que sai e como
 * cada exercicio se chama em portugues.
 *
 * A traducao e nome-a-nome de proposito. A tentativa anterior, por glossario de
 * termos, produzia coisas como "Cross-Bench Dumbbell Pullovers" -> "Com halteres":
 * quando o nucleo do exercicio nao estava no glossario, o modificador virava o nome.
 * Mapa exato nunca inventa; no maximo deixa o nome em ingles.
 */

/** Nao e exercicio de musculacao: alongamento, mobilidade, liberacao miofascial, aquecimento. */
export const PADROES_EXCLUIR = [
  /stretch/i,
  /foam roller/i,
  /blackroll/i,
  /head (tilt|turn)/i,
  /child'?s pose/i,
  /ankle (roll|mobility)/i,
  /dorsiflexion/i,
  /hip circles/i,
  /arabesque/i,
  /pigeon/i,
  /banded ankle/i,
  /calves foam/i,
  /hamstring foam/i,
]

/** Cadastrado no grupo errado la na origem. */
export const EXCLUIR_POR_GRUPO = {
  // o wger marca biceps como musculo primario nesses, mas sao exercicios de costas
  biceps: [
    'Mentzer Pulldown',
    'Incline Chest-Supported Dumbbell Row',
    'Neutral-grip chest pulldown',
    'Single Arm Plank to Row',
    'Inverted Rows',
    'TRX Rows',
  ],
  triceps: ['Dumbbell Hex Press', 'Handstand Pushup'],
  costas: ['Quadriped Arm and Leg Raise'],
  ombro: ['Side-laying interior rotation'],
}

/** Os 12 valores de equipamento que o wger usa. */
export const EQUIPAMENTO = {
  Barbell: 'Barra',
  'SZ-Bar': 'Barra W',
  Dumbbell: 'Halteres',
  Kettlebell: 'Kettlebell',
  'Cable machine': 'Polia',
  Bench: 'Banco',
  'Incline bench': 'Banco inclinado',
  'Pull-up bar': 'Barra fixa',
  'Resistance band': 'Elastico',
  'Swiss Ball': 'Bola suica',
  'Gym mat': 'Colchonete',
  'none (bodyweight exercise)': 'Peso corporal',

  // valores do Free Exercise DB (segunda fonte, chaves minusculas e diferentes do wger)
  'body only': 'Peso corporal',
  barbell: 'Barra',
  dumbbell: 'Halteres',
  cable: 'Polia',
  machine: 'Máquina',
  kettlebells: 'Kettlebell',
  bands: 'Elástico',
  'medicine ball': 'Bola medicinal',
  'exercise ball': 'Bola suíça',
  'foam roll': 'Rolo de espuma',
  'e-z curl bar': 'Barra W',
}

/** en (ou o que o wger cadastrou) -> pt-BR. Nome ausente aqui fica como esta. */
export const TRADUCAO = {
  // ---- peito
  'Bench Press': 'Supino reto com barra',
  'Benchpress Dumbbells': 'Supino reto com halteres',
  'Incline Bench Press - Barbell': 'Supino inclinado com barra',
  'Incline Bench Press - Dumbbell': 'Supino inclinado com halteres',
  'Incline Bench Press - MP': 'Supino inclinado na máquina',
  'Decline Bench Press Barbell': 'Supino declinado com barra',
  'Hammerstrength Decline Chest Press': 'Supino declinado na máquina',
  'Smith Machine Slight Incline Press': 'Supino inclinado no Smith',
  'Chest Press': 'Supino na máquina',
  'Dumbbell Floor Press': 'Supino no chão com halteres',
  'Dumbbell Hex Press': 'Supino hex com halteres',
  'Cross-Bench Dumbbell Pullovers': 'Pullover com halter no banco',
  Butterfly: 'Crucifixo na máquina (peck deck)',
  'Machine chest fly': 'Crucifixo na máquina',
  'Fly With Dumbbells': 'Crucifixo com halteres',
  'Fly With Cable': 'Crucifixo na polia',
  'Seated Cable chest fly': 'Crucifixo sentado na polia',
  'Cable Cross-over': 'Cross-over na polia',
  'Low-Cable Cross-Over - NB': 'Cross-over na polia baixa',
  'Push-Up': 'Flexão de braço',
  'Push-Ups | Decline': 'Flexão de braço declinada',
  'Close-grip Press-ups': 'Flexão de braço pegada fechada',
  'Clap Push-UP': 'Flexão de braço com palma',
  'Russian Push Ups': 'Flexão russa',
  'explosive push ups': 'Flexão explosiva',
  'Weighted push-ups': 'Flexão de braço com peso',
  Dips: 'Mergulho nas paralelas',
  'Inverted Rows': 'Remada invertida',

  // ---- costas
  Deadlifts: 'Levantamento terra',
  'Rack Deadlift': 'Levantamento terra no rack',
  'Kettlebell deadlifts': 'Levantamento terra com kettlebell',
  'Bent Over Rowing': 'Remada curvada com barra',
  'Bent Over Rowing Reverse': 'Remada curvada pegada supinada',
  'Bent Over Dumbbell Rows': 'Remada curvada com halteres',
  'One Arm Bent Row': 'Remada curvada unilateral',
  'Single arm row': 'Remada unilateral com halter',
  'Unilateral Cable row': 'Remada unilateral na polia',
  'Seated Cable Row': 'Remada sentada na polia',
  'Seated Row (Machine)': 'Remada sentada na máquina',
  'Rowing seated, narrow grip': 'Remada sentada pegada fechada',
  'Remo maquina agarre estrecho': 'Remada na máquina pegada fechada',
  'Remo maquina agarre estrecho supino': 'Remada na máquina pegada supinada',
  'Long-Pulley (low Row)': 'Remada baixa na polia',
  'Rowing, T-bar': 'Remada cavalinho',
  'TRX Rows': 'Remada no TRX',
  'Single Arm Plank to Row': 'Remada em prancha unilateral',
  'Incline Chest-Supported Dumbbell Row': 'Remada com apoio no banco inclinado',
  'Dumbbell rear delt row': 'Remada para deltoide posterior',
  'Dumbbell Bent Over Face Pull': 'Face pull curvado com halteres',
  'Face pulls with yellow/green band': 'Face pull com elástico',
  'Pull-ups': 'Barra fixa',
  'Chin Up': 'Barra fixa supinada',
  'Close-grip Lat Pull Down': 'Puxada frontal pegada fechada',
  'Close-grip supinated lat pulldown': 'Puxada supinada pegada fechada',
  'Neutral-grip chest pulldown': 'Puxada com pegada neutra',
  'Modified pulldown': 'Puxada adaptada',
  'Incline bench pulldown': 'Puxada no banco inclinado',
  'Straight-Arm Pulldown (Cable)': 'Pulldown com braço estendido',
  'High-pulley pullover': 'Pullover na polia alta',
  'Rope Pullover/row': 'Pullover na corda',
  Hyperextensions: 'Hiperextensão lombar',
  'Lower Back Extensions': 'Extensão lombar',
  'Back extensión': 'Extensão lombar',
  'Incline Bench Reverse Fly': 'Crucifixo inverso no banco inclinado',
  'Seated rear delt rise': 'Elevação posterior sentado',
  'Dumbbell Hang Power Cleans': 'Power clean com halteres',

  // ---- ombro
  'Shoulder Press, Barbell': 'Desenvolvimento com barra',
  'Shoulder Press, Dumbbells': 'Desenvolvimento com halteres',
  'Shoulder Press, on Machine': 'Desenvolvimento na máquina',
  'Single-arm dumbbell shoulder press': 'Desenvolvimento unilateral com halter',
  'Overhead Barbell Press': 'Desenvolvimento acima da cabeça',
  'Military Press mit SZ-Bar': 'Desenvolvimento militar com barra W',
  'Smith Press': 'Desenvolvimento no Smith',
  'Push Press': 'Push press',
  'Clean and Press': 'Clean and press',
  'Barbell Clean and press': 'Clean and press com barra',
  'Devil’s Press': "Devil's press",
  'Trap press': 'Desenvolvimento para trapézio',
  'Lateral Raises': 'Elevação lateral com halteres',
  'Machine Lateral Raise': 'Elevação lateral na máquina',
  'Machine Side Lateral Raises': 'Elevação lateral na máquina',
  'Cable Lateral Raises (Single Arm)': 'Elevação lateral unilateral na polia',
  'Lateral Rows on Cable, One Armed': 'Elevação lateral unilateral na polia',
  'Front Raises': 'Elevação frontal com halteres',
  'Cable Front Raise with a small bar': 'Elevação frontal na polia',
  'Shoulder Raise (Dumbbell)': 'Elevação de ombro com halteres',
  'Rear Delt Raises': 'Elevação posterior com halteres',
  'Cable Rear Delt Fly': 'Crucifixo inverso na polia',
  'Upright Row, SZ-bar': 'Remada alta com barra W',
  'Upright Row w/ Dumbbells': 'Remada alta com halteres',
  'Upright Row, on Multi Press': 'Remada alta na máquina',
  'Bent High Pulls': 'Puxada alta curvada',
  'Shrugs, Barbells': 'Encolhimento com barra',
  'Shrugs, Dumbbells': 'Encolhimento com halteres',
  'Shoulder Shrug': 'Encolhimento de ombros',
  'Bus Drivers': 'Bus driver (rotação com anilha)',
  'Handstand Pushup': 'Flexão em parada de mão',
  'Hindu Pushups': 'Flexão hindu',
  'Tuck planche': 'Planche agrupado',
  'Arnold Dumbbell Press': 'Desenvolvimento Arnold',

  // ---- biceps
  'Biceps Curls With Barbell': 'Rosca direta com barra',
  'Preacher Curl': 'Rosca Scott',
  'Biceps Curls With SZ-bar': 'Rosca direta com barra W',
  'Biceps Curls With Dumbbell': 'Rosca alternada com halteres',
  'Alternating Biceps Curls With Dumbbell': 'Rosca alternada com halteres',
  'Alternating bicep curls': 'Rosca alternada',
  'Biceps Curl With Cable': 'Rosca na polia',
  'Straight Bar Cable Curls': 'Rosca na polia com barra reta',
  'Cable Concentration Curl': 'Rosca concentrada na polia',
  'Hammer Curls': 'Rosca martelo',
  'Alternating dumbbell hammer curl': 'Rosca martelo alternada',
  'Hammercurls on Cable': 'Rosca martelo na polia',
  'Reverse Grip Barbell Curls': 'Rosca inversa com barra',
  'Dumbbell wide bicep curls': 'Rosca com pegada aberta',
  'Dumbbell bicep curl to press': 'Rosca com desenvolvimento',
  'one-handed kettlebell curls': 'Rosca unilateral com kettlebell',
  'Seated W Curl': 'Rosca sentado com barra W',
  'Biceps with TRX': 'Rosca no TRX',

  // ---- triceps
  'Barbell Triceps Extension': 'Tríceps testa com barra',
  'Skullcrusher SZ-bar': 'Tríceps testa com barra W',
  'Triceps Overhead (Dumbbell)': 'Tríceps francês com halter',
  'Triceps Extensions on Cable': 'Tríceps na polia',
  'Triceps Pushdown': 'Tríceps pulley',
  'Tricep Pushdown on Cable': 'Tríceps pulley na polia',
  'Tricep Rope Pushdowns': 'Tríceps corda',
  'High-Cable Cross Tricep Extention - NB': 'Tríceps cruzado na polia alta',
  'Bench Press Narrow Grip': 'Supino pegada fechada',
  'Dips Between Two Benches': 'Mergulho entre bancos',
  'Floor dips': 'Mergulho no solo',

  // ---- pernas
  'Barbell Full Squat': 'Agachamento livre com barra',
  'Front Squats': 'Agachamento frontal',
  'Dumbbell Front Squat': 'Agachamento frontal com halteres',
  'Dumbbell Goblet Squat': 'Agachamento goblet',
  'Dumbbell Side Squat': 'Agachamento lateral com halteres',
  'Box squat': 'Agachamento no caixote',
  'Slow Squat': 'Agachamento lento',
  'Isometric Squat to Failure': 'Agachamento isométrico até a falha',
  'Smith machine squat': 'Agachamento no Smith',
  'Smith Machine Split Squat': 'Agachamento búlgaro no Smith',
  'Bulgarian Squat with Dumbbells': 'Agachamento búlgaro com halteres',
  'Bulgarian split squats left': 'Agachamento búlgaro',
  'Pistol Squat': 'Agachamento pistol',
  'Reverse V-Squat': 'Agachamento V invertido',
  'Pendular hack': 'Agachamento hack pendular',
  'Leg Press': 'Leg press',
  'Leg Presses (narrow)': 'Leg press pegada fechada',
  'Leg Press on Hackenschmidt Machine': 'Leg press no hack',
  'Leg Extension': 'Cadeira extensora',
  'Leg Curls (laying)': 'Mesa flexora',
  'Leg Curls (sitting)': 'Cadeira flexora',
  'Leg Curls (standing)': 'Flexora em pé',
  'Leg Curl': 'Flexora',
  'Machine Leg Flexion': 'Flexora na máquina',
  'Reverse Nordic Curl': 'Nórdico invertido',
  'Machine Hip Abduction': 'Cadeira abdutora',
  'Seated Hip Adduction': 'Cadeira adutora',
  Lunges: 'Afundo',
  'Reverse lunges': 'Afundo reverso',
  'Dumbbell Rear Lunge': 'Afundo reverso com halteres',
  'Dumbbell Lunges Walking': 'Afundo caminhando com halteres',
  'Barbell Step Back Lunge': 'Afundo reverso com barra',
  'Sliding Lateral Lunge': 'Afundo lateral deslizante',
  'Single-Leg Lunge with Kettlebell:': 'Afundo unilateral com kettlebell',
  'Step-ups': 'Step up',
  'Lateral Push Off': 'Impulsão lateral',
  'Romanian Deadlift': 'Stiff (levantamento terra romeno)',
  'Dumbbell Romanian Deadlift': 'Stiff com halteres',
  'Sumo Deadlift': 'Levantamento terra sumô',
  'Dumbbell sumo deadlift': 'Levantamento terra sumô com halteres',
  'kettlebell sumo deadlift': 'Levantamento terra sumô com kettlebell',
  'Single-Leg Deadlift with Dumbbell': 'Levantamento terra unilateral com halter',
  'Kettlebell One Legged Deadlift': 'Levantamento terra unilateral com kettlebell',
  'Good Morning': 'Bom dia (good morning)',
  'Kettlebell Swing': 'Swing com kettlebell',
  'dumbbell snatch': 'Arranco com halter',
  'Dumbbell Hip Thrust': 'Elevação pélvica com halter',
  'Glute Bridge': 'Ponte de glúteo',
  '(D) Puente de glúteos': 'Ponte de glúteo',
  'Cable glute extension': 'Extensão de glúteo na polia',
  'Kneeling kickbacks': 'Coice de glúteo ajoelhado',
  'Dumbbell donkey kick': 'Coice de glúteo com halter',
  'rubber band glute kickback': 'Coice de glúteo com elástico',
  'Single-leg side glute press': 'Glúteo unilateral no leg press',
  'Double Leg Calf Raise': 'Panturrilha em pé',
  'Hamstring Kicks': 'Chute de posterior',
  'Marching High Knees': 'Marcha com joelhos altos',
  'Jumping Jacks': 'Polichinelo',
  'Wall balls': 'Wall ball',
  'Hip Crossover': 'Rotação de quadril no solo',
  'Hip-Out and Hip-In Lateral Steps': 'Passo lateral com elástico',
  'Band Terminal Knee extension': 'Extensão terminal de joelho com elástico',
  'Single-Leg Soft-Landing Holds': 'Aterrissagem unilateral',
  'Knee to Chest Stretch': 'Joelho ao peito',
}
